
healthCheckTimeout: 500

logLevel: debug

# note: quite entertaining, but they impact further generation
# sendLoadingState: true

apiKeys:
  - "sk-d2V0bmF0dXJhbGx5bHVuZ3NwYXJ0aWN1bGFyc2ltcGxlZnV0dXJlbGVuZ3RocG9z"

models:
  dolphin24B:
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "/models/dolphin/Dolphin3.0-R1-Mistral-24B-awq-asym"
    cmd: >
      docker run 
        --runtime nvidia 
        --gpus all
        --name ${MODEL_ID}
        --rm
        --init
        -v C:/Users/albin/Documents/Projects/llm/models:/models
        --env "HF_TOKEN=$HF_TOKEN" 
        -p ${PORT}:8000
        vllm/vllm-openai:v0.14.1 
        --model /models/dolphin/Dolphin3.0-R1-Mistral-24B-awq-asym 
        --max-model-len 12K
        --gpu-memory-utilization 0.5
    cmdStop: docker stop ${MODEL_ID}
  dolphin8B:
    aliases:
      - "gpt-5"
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "/models/dolphin/Dolphin3.0-Llama3.1-8B-awq-asym"
    cmd: >
      docker run 
        --runtime nvidia 
        --gpus all
        --name ${MODEL_ID}
        --rm
        --init
        -v C:/Users/albin/Documents/Projects/llm/models:/models
        --env "HF_TOKEN=$HF_TOKEN" 
        -p ${PORT}:8000
        vllm/vllm-openai:v0.14.1 
        --model /models/Dolphin3.0-Llama3.1-8B-awq-asym 
        --max_model_len 24K
        --gpu-memory-utilization 0.4
    cmdStop: docker stop ${MODEL_ID}
  dolphin3B:
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "/models/dolphin/Dolphin3.0-Qwen2.5-3B-awq-asym"
    cmd: >
      docker run 
      --runtime nvidia 
      --gpus all
      --name ${MODEL_ID}
      --rm
      --init
      -v C:/Users/albin/Documents/Projects/llm/models:/models
      --env "HF_TOKEN=$HF_TOKEN" 
      -p ${PORT}:8000
      vllm/vllm-openai:v0.14.1 
      --model /models/dolphin/Dolphin3.0-Qwen2.5-3B-awq-asym 
      --max_model_len 2K
      --gpu-memory-utilization 0.5
    cmdStop: docker stop ${MODEL_ID}
  dolphin1.5B:
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "/models/dolphin/Dolphin3.0-Qwen2.5-1.5B-awq-asym"
    cmd: >
      docker run 
      --runtime nvidia 
      --gpus all
      --name ${MODEL_ID}
      --rm
      --init
      -v C:/Users/albin/Documents/Projects/llm/models:/models
      --env "HF_TOKEN=$HF_TOKEN" 
      -p ${PORT}:8000
      vllm/vllm-openai:v0.14.1 
      --model /models/dolphin/Dolphin3.0-Qwen2.5-1.5B-awq-asym 
      --max-model-len 4K
      --gpu-memory-utilization 0.5
    cmdStop: docker stop ${MODEL_ID}
  dolphin0.5B:
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "/models/dolphin/Dolphin3.0-Qwen2.5-0.5B-awq-asym"
    cmd: >
      docker run 
      --runtime nvidia 
      --gpus all
      --name ${MODEL_ID}
      --rm
      --init
      -v C:/Users/albin/Documents/Projects/llm/models:/models
      --env "HF_TOKEN=$HF_TOKEN" 
      -p ${PORT}:8000
      vllm/vllm-openai:v0.14.1 
      --model /models/dolphin/Dolphin3.0-Qwen2.5-0.5B-awq-asym 
      --max_model_len 2K
      --gpu-memory-utilization 0.5
    cmdStop: docker stop ${MODEL_ID}
  sw3-6.7B-instruct:
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "/models/gpt-sw3-6.7b-v2-instruct"
    cmd: >
      docker run 
      --runtime nvidia 
      --gpus all
      --name ${MODEL_ID}
      --rm
      --init
      -v C:/Users/albin/Documents/Projects/llm/models:/models
      --env "HF_TOKEN=$HF_TOKEN" 
      -p ${PORT}:8000
      vllm/vllm-openai:v0.14.1 
      --model /models/gpt-sw3-6.7b-v2-instruct
      --tokenizer AI-Sweden-Models/gpt-sw3-6.7b-v2-instruct
      --hf-config-path AI-Sweden-Models/gpt-sw3-6.7b-v2-instruct
    cmdStop: docker stop ${MODEL_ID}
  sw3-20B-instruct:
    proxy: "http://host.docker.internal:${PORT}"
    useModelName: "AI-Sweden-Models/gpt-sw3-20b-instruct"
    cmd: >
      docker run 
      --runtime nvidia 
      --gpus all
      --name ${MODEL_ID}
      --rm
      --init
      -v C:/Users/albin/Documents/Projects/llm/models:/models
      --env "HF_TOKEN=$HF_TOKEN" 
      -p ${PORT}:8000
      vllm/vllm-openai:v0.14.1 
      --model /models/sw3-20B-instruct
      --tokenizer AI-Sweden-Models/gpt-sw3-20b-instruct
      --hf-config-path AI-Sweden-Models/gpt-sw3-20b-instruct
    cmdStop: docker stop ${MODEL_ID}

